# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-08 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='modify_date',
        ),
    ]
